###
### AUTH ENDPOINT (LOGIN)
###
# @name adminLogin
@adminToken = {{adminLogin.response.body.data.access_token}}

POST {{baseUrl}}/auth
Content-Type: {{contentType}}

{
  "phone": "09016000000",
  "password": "12345678"
}

###
### WALLET ENDPOINTS
###
GET {{baseUrl}}/wallet/all
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

###
### TRANSACTION ENDPOINTS
###
GET {{baseUrl}}/transaction/all
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}

### 

PUT {{baseUrl}}/transaction/confirm/57
Content-Type: {{contentType}}
Authorization: Bearer {{adminToken}}