###
### AUTH ENDPOINT (LOGIN)
###
# @name login
@loginToken = {{login.response.body.data.access_token}}


POST {{baseUrl}}/auth
Content-Type: {{contentType}}

{
  "phone": "09071046909",
  "password": "12345678"
}

###
### USER ENDPOINT 
###
# @name reg
@regToken = {{reg.response.body.access_token}}

POST {{baseUrl}}/user/new
Content-Type: {{contentType}}

{
  "phone": "09071046909",
  "password": "12345678"
}


###
### WALLET ENDPOINTS
###
POST {{baseUrl}}/wallet/new
Content-Type: {{contentType}}
Authorization: Bearer {{loginToken}}

{
  "curr": "EUR"
}

### MAKE DEPOSIT
PUT {{baseUrl}}/wallet
Content-Type: {{contentType}}
Authorization: Bearer {{loginToken}}

{ 
  "operator": "DEPOSIT",
  "amount": 100000000,                       
    "wallet": "EUR"
}

### MAKE TRANSFER
PUT {{baseUrl}}/wallet
Content-Type: {{contentType}}
Authorization: Bearer {{loginToken}}

{
  "operator": "TRANSFER",
  "amount": 1000000,
    "wallet": "EUR",
    "to": "08097303617",
    "desc": "from me"
}


