###
### AUTH ENDPOINT (LOGIN)
###
# @name login
@loginToken = {{login.response.body.data.access_token}}


POST {{baseUrl}}/auth
Content-Type: {{contentType}}

{
  "phone": "08097303617",
  "password": "12345678"
}

###
### USER ENDPOINT 
###
# @name reg
@regToken = {{reg.response.body.access_token}}

POST {{baseUrl}}/user/new
Content-Type: {{contentType}}

{
  "phone": "09073036221",
  "password": "12345678"
}


###
### WALLET ENDPOINTS
###
POST {{baseUrl}}/wallet/new
Content-Type: {{contentType}}
Authorization: Bearer {{regToken}}

{
  "curr": "EUR"
}

### MAKE DEPOSIT
PUT {{baseUrl}}/wallet
Content-Type: {{contentType}}
Authorization: Bearer {{regToken}}

{
  "operator": "deposit",
  "amount": 300000,
    "wallet": "NGN"
}

### MAKE TRANSFER
PUT {{baseUrl}}/wallet
Content-Type: {{contentType}}
Authorization: Bearer {{regToken}}

{
  "operator": "transfer",
  "amount": 300000,
    "wallet": "NGN",
    "to": "090710469w09"
}


