#  @token = {{loginAPI.response.body.token}}
POST {{baseUrl}}/user/new
Content-Type: {{contentType}}

{
  "phone": "080973w0s361743",
  "password": "12345678"
}

###
GET {{baseUrl}}/user/1
Content-Type: {{contentType}}
